### ISSUE TITLE
add-deleted-users-module

### ISSUE THREAD

**Issue by wizardrevenge** [WizardRRR/crud-javascript#1]
## Añadir un modulo de usuarios eliminados, este modulo debería tener :

- vista de usuarios eliminados
- restaurar un usuario eliminado

debora

**Comment by deboraabarca** [comment]
hice la vista de los usuarios eliminados ,pero para restaurar ,se me está complicando :/

**Comment by wizardrevenge** [comment]
![image](https://github.com/WizardRRR/crud-javascript/assets/74883427/178d3e59-d6b6-4808-a949-30fa268c8a5a)
