### ISSUE TITLE
styles/card-user

### ISSUE THREAD

**Issue by wizardrevenge** [WizardRRR/crud-javascript#3]
## estilizar tarjeta de usuario
- añadir fecha de creación 
 - añadir fecha en la cual se edito el usuario si es que se edito
 
 anderson huertas

**Comment by RyuKinneret** [comment]
royer debe ser algo asi ???? 
![image](https://github.com/WizardRRR/crud-javascript/assets/159345069/3ab9cfdd-1563-4473-b786-896d2cd20977)

**Comment by wizardrevenge** [comment]
pues claro

como tal la fecha ya esta es el created_at y el update_at respectivamente

**Comment by RyuKinneret** [comment]
en resumen debe de salir abajito de estos datos y tambien en el localstorage?
![image](https://github.com/WizardRRR/crud-javascript/assets/159345069/6d16b1da-d068-4557-b562-83d5e149b6c8)

**Comment by wizardrevenge** [comment]
los datos ya estan en el local storage
la tarea era pintarla nada mas por eso decia que era una tarea sencilla
