### ISSUE TITLE
confirmation-modal-for-actions

### ISSUE THREAD

**Issue by wizardrevenge** [WizardRRR/crud-javascript#8]
## Modal de confirmación para acciones

- cuando actualizas un usuario
- cuando eliminar un usuario

Cesar

**Comment by Dicesaro** [comment]
Royer...
En resumen lo que tengo que hacer es algo parecido a esto ? 🤔

Como un tipo de alert ?

![image](https://github.com/WizardRRR/crud-javascript/assets/127168347/f3cb6e3f-6d44-4936-a23c-d6073408bb49)

**Comment by wizardrevenge** [comment]
si así es

**Comment by Dicesaro** [comment]
https://senatipe-my.sharepoint.com/:v:/g/personal/1472437_senati_pe/EVYzY7zKdp5BvU63SYOOBwEBEol8OcH7C6pHCCntQuw5bA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=zeDScE

Royer ya casi lo tengo , ahora solo me falta darle estilos al alert . 

Como lo podria hacer usando CSS Y DOM ??

En la tarde tendras libre para que me puedas dar un asesoramiento ?

**Comment by Dicesaro** [comment]
y si solo uso el .alert() del window ? 🫥

**Comment by wizardrevenge** [comment]
terrible manito vaya , estaba entrentenido en el proyecto del map, mañana para todos

**Comment by Dicesaro** [comment]
Terrible 

Pero si habrá reu hoy a las 5 pm ?

**Comment by wizardrevenge** [comment]
ya hubo 🤨
