### ISSUE TITLE
add-data-to-user

### ISSUE THREAD

**Issue by wizardrevenge** [WizardRRR/crud-javascript#9]
## añadir datos al usuario
- color: es el color de la barra de su tarjeta
- uri_image: es la url que representa su perfil
- city: ciudad

**Comment by nicolasdelrosario** [comment]
Feature solved.

**Comment by wizardrevenge** [comment]
🤨 se cierra cuando se verifique

**Comment by wizardrevenge** [comment]
por cierto no veo el commit

**Comment by wizardrevenge** [comment]
![image](https://github.com/WizardRRR/crud-javascript/assets/74883427/66617002-6079-4490-9bd7-97cf58646a57)

Observaciones:
1. no se muestra el color que elijo al seleccionarlo en el input 
2. no controla si realmente es una URL en el campo
3. sigue los estándares en la codificación revisa la wiki del repo

Añade
4. Al ser una actualización los usuarios antiguos no tienen foto debe mostrar un placeholder en la "card" para que no se vea vacío.

**Comment by nicolasdelrosario** [comment]
Puedes revisar los nuevos cambios pls

**Comment by wizardrevenge** [comment]
han roto main tu causa XD parece que hay conflictos en archivos

**Comment by nicolasdelrosario** [comment]
XD
